# Generated by Django 5.1.5 on 2025-02-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0003_mazequestion_hint_available_mazequestion_score_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mazequestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움')], default='easy', max_length=10),
        ),
    ]
