# Generated by Django 5.1.5 on 2025-02-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0004_alter_mazequestion_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mazequestion',
            old_name='difficulty',
            new_name='level',
        ),
    ]
