# Generated by Django 5.1.5 on 2025-02-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0007_alter_mazeprogress_current_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazequestion',
            name='accepted_answers',
            field=models.TextField(blank=True, help_text='여러 정답이 허용될 경우,', verbose_name='허용 정답 (쉼표로 구분)'),
        ),
        migrations.AlterField(
            model_name='mazequestion',
            name='level',
            field=models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움'), ('puzzle', '퍼즐/로직'), ('mc', '다지선다형')], default='easy', max_length=6),
        ),
    ]
