# Generated by Django 5.1.5 on 2025-02-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0008_mazequestion_accepted_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazequestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maze_images/'),
        ),
        migrations.AlterField(
            model_name='mazequestion',
            name='level',
            field=models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움')], default='easy', max_length=6),
        ),
    ]
