# Generated by Django 5.1.5 on 2025-02-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0009_mazequestion_image_alter_mazequestion_level'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mazequestion',
            name='unique_maze_question_order',
        ),
        migrations.AddConstraint(
            model_name='mazequestion',
            constraint=models.UniqueConstraint(fields=('order', 'level'), name='unique_maze_question_order'),
        ),
    ]
