# Generated by Django 5.1.5 on 2025-02-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0011_alter_mazequestion_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazequestion',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_step', to='maze.mazequestion'),
        ),
        migrations.AddField(
            model_name='mazequestion',
            name='story_next',
            field=models.TextField(blank=True, null=True),
        ),
    ]
