# Generated by Django 5.1.5 on 2025-02-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0012_mazequestion_next_question_mazequestion_story_next'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mazequestion',
            old_name='story_next',
            new_name='story_text',
        ),
    ]
