# Generated by Django 5.1.5 on 2025-02-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0015_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
