# Generated by Django 5.1.5 on 2025-03-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0016_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mazequestion',
            name='accepted_answers',
            field=models.TextField(blank=True, help_text='여러 정답이 허용될 경우 쉼표로 구분', verbose_name='허용 정답 (쉼표로 구분)'),
        ),
    ]
