# Generated by Django 5.1.5 on 2025-02-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_mazequestion_playerprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprogress',
            name='completed_questions',
        ),
        migrations.RemoveField(
            model_name='playerprogress',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='playerprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='MazeQuestion',
        ),
        migrations.DeleteModel(
            name='PlayerProgress',
        ),
    ]
