# Generated by Django 5.1.5 on 2025-02-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_cateogry_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogry',
            new_name='Category',
        ),
    ]
