# Generated by Django 5.1.5 on 2025-02-08 06:45

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_post_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=board.models.post_file_path),
        ),
    ]
