# Generated by Django 5.1.5 on 2025-02-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MazeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('hint', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
    ]
