# Generated by Django 5.1.5 on 2025-02-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazequestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='mazequestion',
            name='time_limit',
            field=models.IntegerField(default=60),
        ),
    ]
