# Generated by Django 5.1.5 on 2025-02-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0002_mazequestion_difficulty_mazequestion_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazequestion',
            name='hint_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mazequestion',
            name='score_value',
            field=models.IntegerField(default=10),
        ),
    ]
